/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  TabActivateEvent,
} from './components/app-tab1/app-tab1';

export namespace Components {
  interface AppTab1 {
    'active': boolean;
    'name': string;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyTabs {}
  interface YearPicker {
    'year': number;
  }
}

declare global {


  interface HTMLAppTab1Element extends Components.AppTab1, HTMLStencilElement {}
  var HTMLAppTab1Element: {
    prototype: HTMLAppTab1Element;
    new (): HTMLAppTab1Element;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLMyTabsElement extends Components.MyTabs, HTMLStencilElement {}
  var HTMLMyTabsElement: {
    prototype: HTMLMyTabsElement;
    new (): HTMLMyTabsElement;
  };

  interface HTMLYearPickerElement extends Components.YearPicker, HTMLStencilElement {}
  var HTMLYearPickerElement: {
    prototype: HTMLYearPickerElement;
    new (): HTMLYearPickerElement;
  };
  interface HTMLElementTagNameMap {
    'app-tab1': HTMLAppTab1Element;
    'my-component': HTMLMyComponentElement;
    'my-tabs': HTMLMyTabsElement;
    'year-picker': HTMLYearPickerElement;
  }
}

declare namespace LocalJSX {
  interface AppTab1 {
    'active'?: boolean;
    'name'?: string;
    'onTabActivate'?: (event: CustomEvent<TabActivateEvent>) => void;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface MyTabs {}
  interface YearPicker {
    'year'?: number;
  }

  interface IntrinsicElements {
    'app-tab1': AppTab1;
    'my-component': MyComponent;
    'my-tabs': MyTabs;
    'year-picker': YearPicker;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-tab1': LocalJSX.AppTab1 & JSXBase.HTMLAttributes<HTMLAppTab1Element>;
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'my-tabs': LocalJSX.MyTabs & JSXBase.HTMLAttributes<HTMLMyTabsElement>;
      'year-picker': LocalJSX.YearPicker & JSXBase.HTMLAttributes<HTMLYearPickerElement>;
    }
  }
}


